#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Task App', '1.0');

try {
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(Exception $e) {
    echo $e->getMessage();
    echo 'Could not connect to the Database';
    exit(1);
}

$dbAdapter = new App\DatabaseAdapter($pdo);

$app->add(new App\ShowCommand($dbAdapter));
$app->add(new App\AddCommand($dbAdapter));
$app->add(new App\CompleteCommand($dbAdapter));

$app->run();
